# 서버 포트 설정
server:
  port: 7777

spring:
  #cache(Redis) 설정
  cache:
    type: redis
  redis:
    host: 211.62.204.27
    port: 6379
  # Datasource 설정    
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://211.62.204.27:3306/auth?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: gateway
    password: gateway12
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
  #kafka 연동
  cloud:
    bus:
      enabled: true
  # RabbitMQ 설정
  rabbitmq:
    host: 211.62.204.27
    port: 5672
    username: gateway
    password: gateway
# 로그 설정
logging:
  config: classpath:${spring.profiles.active}/log4j2.yml   