# 서버 포트
server:
  port: 8888
  
# 로그 레벨 설정
logging:
  level:
    root: INFO
    
management:
  endpoints:
    web:
      exposure:
        include: "*"   
    
#사용자 정의 속성
services:
  api:
    route-url: http://localhost:8080/api/service/v1/routes/

jwt:
  secret-key: 1EB87004BBEA8377C5F584DAE670AA293E6A856C2B4B4708E63B713EBDABBEF8
  issuer: saruan