server:
  port: 8761

spring:
  cloud:
    clients:
      hostname: eureka-server

eureka:
  instance:
    hostname: ${spring.cloud.clients.hostname}
  client:
    egisterWithEureka: false
    fetchRegistry: false