# 서버 포트
server:
  port: 8888

# 로그 레벨 설정
logging:
  level:
    root: INFO

#사용자 정의 속성
services:
  api:
    route-url: http://localhost:8080/api/service/v1/routes/app/
  auth:
    host: http://localhost:7777
    check_token-uri: /oauth/check_token

# 기본 서비스
gateway:
  service:
    routing:
      path: /gateway/routes/
      url:  http://localhost:8080/api/service/v1/routes/
    app:
      path: /gateway/apps/
      url:  http://localhost:8080/api/service/v1/app/
    filter:
      path: /gateway/filters/
      url:  http://localhost:8080/api/service/v1/filter/
    saml:
      path: /gateway/saml/
      url:  http://localhost:7777/auth/v1.0/oauth/saml
      filter: SAMLFilter
    token:
      path: /gateway/token/
      url:  http://localhost:7777/oauth/token
      filter: TokenFilter

# 인증 키관리
jwt:
  secret-key: 1EB87004BBEA8377C5F584DAE670AA293E6A856C2B4B4708E63B713EBDABBEF8
  issuer: saruan
oauth:
  client-id: Basic Y2xpZW50MjpwYXNzd29yZA==

#KAFKA 연동
spring:
  cloud:
    bus:
      enabled: true
    gateway:
      plugin:
        config:
          log-request: true
          read-request-data: true # this setting will read all request data
          read-response-data: true
  kafka:
    bootstrap-servers:
      - http://localhost:9092