# 서버 포트
server:
  port: 8888
  
# 로그 레벨 설정
logging:
  level:
    root: INFO

#사용자 정의 속성
services:
  api:
    route-url: http://localhost:8080/api/service/v1/routes/app/
  auth:
    host: http://localhost:7777
    check_token-uri: /oauth/check_token

# 인증 키관리
jwt:
  secret-key: 1EB87004BBEA8377C5F584DAE670AA293E6A856C2B4B4708E63B713EBDABBEF8
  issuer: saruan  
oauth:
  client-id: Basic Y2xpZW50MjpwYXNzd29yZA==

#RabbitMQ 연동
spring:
  rabbitmq:       # RabbitMQ 정보 수정.
    host: localhost   
    port: 5672
    username: guest
    password: guest