# 서버 포트 설정
server:
  port: 8080

spring:
  # Datasource 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gateway?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
  jpa:
    database-platform: com.kbds.serviceapi.framework.dialect.CustomMysqlDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
  #kafka 연동
  cloud:
    bus:
      enabled: true
  # RabbitMQ 설정
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# 로그 설정
logging:
  config: classpath:${spring.profiles.active}/log4j2.yml

#사용자 정의 속성
services:
  bus:
    host: http://localhost:9999/
    refresh: /actuator/bus-refresh

#인증 키관리    
jwt:
  secret-key: 1EB87004BBEA8377C5F584DAE670AA293E6A856C2B4B4708E63B713EBDABBEF8
  issuer: saruan