# 서버 포트 설정
server:
  port: 8080

spring:  
  # Datasource 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gateway?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
  # RabbitMQ 설정
  rabbitmq:       
    host: localhost   
    port: 5672
    username: guest
    password: guest

# 로그 설정
logging:
  config: classpath:${spring.profiles.active}/log4j2.yml
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
              
# 사용자 정의 설정
gateway:
  cluster:
    refreshUrl: http://localhost:9999/actuator/bus-refresh
    
jwt:
  secret-key: 1EB87004BBEA8377C5F584DAE670AA293E6A856C2B4B4708E63B713EBDABBEF8
  issuer: saruan
  
eureka:
  client:
    service-url:
      defaultZone: http://Eureka:8761/eureka/